name: deploy_gcsst_ui

on:
  push:
    tags:
      - "gcsst-ui-v*.*.*"
  workflow_dispatch:

jobs:
  deploy:
    name: deploy_gcsst_ui
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get_latest_tags
        id: get_latest_tags
        run: |
          echo "Listing all tags:"
          git tag --list

          GCSST_TAG=$(git tag --list "gcsst-v*" --sort=-creatordate | head -n 1)
          GCSST_UI_TAG=$(git tag --list "gcsst-ui-v*" --sort=-creatordate | head -n 1)

          GCSST_VERSION=$(echo "$GCSST_TAG" | sed 's/gcsst-v//')
          GCSST_UI_VERSION=$(echo "$GCSST_UI_TAG" | sed 's/gcsst-ui-v//')

          echo "::set-output name=GCSST_VERSION::${GCSST_VERSION}"
          echo "::set-output name=GCSST_UI_VERSION::${GCSST_UI_VERSION}"

      - name: display_env
        run: |
          echo "GCSST_VERSION: $GCSST_VERSION"
          echo "GCSST_UI_VERSION: $GCSST_UI_VERSION"

      - name: deploy
        uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJ_ID }}
          working-directory: gcsst-ui
        env:
          GCSST_VERSION: ${{ steps.get_latest_tags.outputs.GCSST_VERSION }}
          GCSST_UI_VERSION: ${{ steps.get_latest_tags.outputs.GCSST_UI_VERSION }}
