name: deploy_gcsst_ui

on:
  push:
    tags:
      - 'gcsst-ui-v*.*.*'
  workflow_dispatch:

jobs:
  deploy:
    name: deploy_gcsst_ui
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: get_latest_tags
        run: |
          GCSST_TAG=$(git tag --list "gcsst-v*" --sort=-creatordate | head -n 1)
          GCSST_UI_TAG=$(git tag --list "gcsst-ui-v*" --sort=-creatordate | head -n 1)

          GCSST_VERSION=$(echo "$GCSST_TAG" | sed 's/gcsst-v//')
          GCSST_UI_VERSION=$(echo "$GCSST_UI_TAG" | sed 's/gcsst-ui-v//')

          echo "GCSST_VERSION=${GCSST_VERSION}" >> gcsst-ui/.env
          echo "GCSST_UI_VERSION=${GCSST_UI_VERSION}" >> gcsst-ui/.env

      - name: display_env
        run: cat gcsst-ui/.env

      - name: deploy
        uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJ_ID }}
          working-directory: gcsst-ui
